Fix dict error when notify_once selected, close #4
nio-blocks/merge_streams pull request #16
Opened 2017-07-12 17:53 UTC by kyliedale

2017-07-12 18:15 UTC, mattdodge requested changes
What does this fix exactly? It looks like a no-op to me at first glance. Can you add a test that was failing before but passes with this fix to make it clear?

2017-07-12 22:30 UTC, mattdodge commented
To make this truly thread safe we should add a `defaultdict` of `Lock`s that we can wrap around that for loop in the `process_group_signals` method.

2017-07-13 17:02 UTC, dorzel commented
Resolves #15

2017-07-14 23:24 UTC, mattdodge approved these changes

2017-07-14 23:24 UTC, merged